In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector

vector = torch.tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix

MATRIX = torch.tensor([[7, 8],
                      [2, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 2, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# tensor

TENSOR = torch.tensor([[[1, 2, 3],
                      [3, 6, 9],
                      [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
# Random tensors

random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.1561, 0.5730, 0.8356, 0.7339],
        [0.4835, 0.4299, 0.5789, 0.0765],
        [0.6595, 0.7949, 0.0055, 0.4080]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, # what dtype (float 32)
                               device="cpu", # what device your tensor is on
                               requires_grad=False) # track grads
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16, # what dtype (float 32)
                               device="cpu", # what device your tensor is on
                               requires_grad=False) # track grads
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.long)
int_32_tensor, int_32_tensor.dtype

(tensor([3, 6, 9]), torch.int64)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
some_tensor = torch.rand(size=(1, 3, 4),
                         dtype=torch.float16)

some_tensor

tensor([[[0.5820, 0.9360, 0.6992, 0.5542],
         [0.5854, 0.4941, 0.3999, 0.0063],
         [0.4053, 0.3711, 0.6455, 0.8105]]], dtype=torch.float16)

In [ ]:
print(f"Data Type: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}" )

Data Type: torch.float16
Shape: torch.Size([1, 3, 4])
Device: cpu


In [ ]:
# manipulating a tensor

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [ ]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
x = torch.arange(start=0, end=101, step=10)
x, x.dtype

(tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]), torch.int64)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(50.)

In [ ]:
torch.argmax(x)

tensor(10)

In [ ]:
x[10]

tensor(100)

In [ ]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape(2, 1, 5)
x_reshaped, x_reshaped.shape

(tensor([[[ 1.,  2.,  3.,  4.,  5.]],
 
         [[ 6.,  7.,  8.,  9., 10.]]]),
 torch.Size([2, 1, 5]))

In [ ]:
# change view
z = x.view(2, 1, 5)

z, x

(tensor([[[ 1.,  2.,  3.,  4.,  5.]],
 
         [[ 6.,  7.,  8.,  9., 10.]]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
z[:, :, 0] = 5
z, x

(tensor([[[ 5.,  2.,  3.,  4.,  5.]],
 
         [[ 5.,  7.,  8.,  9., 10.]]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)

x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [24]:
import torch
t = torch.arange(1., 211.)
t

tensor([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
         25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
         37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
         49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
         61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
         73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
         85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
         97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106., 107., 108.,
        109., 110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
        121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
        133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143., 144.,
        145., 146., 147., 148., 149., 15

In [25]:
t = t.reshape(5, 6, 7)
t, t.shape

(tensor([[[  1.,   2.,   3.,   4.,   5.,   6.,   7.],
          [  8.,   9.,  10.,  11.,  12.,  13.,  14.],
          [ 15.,  16.,  17.,  18.,  19.,  20.,  21.],
          [ 22.,  23.,  24.,  25.,  26.,  27.,  28.],
          [ 29.,  30.,  31.,  32.,  33.,  34.,  35.],
          [ 36.,  37.,  38.,  39.,  40.,  41.,  42.]],
 
         [[ 43.,  44.,  45.,  46.,  47.,  48.,  49.],
          [ 50.,  51.,  52.,  53.,  54.,  55.,  56.],
          [ 57.,  58.,  59.,  60.,  61.,  62.,  63.],
          [ 64.,  65.,  66.,  67.,  68.,  69.,  70.],
          [ 71.,  72.,  73.,  74.,  75.,  76.,  77.],
          [ 78.,  79.,  80.,  81.,  82.,  83.,  84.]],
 
         [[ 85.,  86.,  87.,  88.,  89.,  90.,  91.],
          [ 92.,  93.,  94.,  95.,  96.,  97.,  98.],
          [ 99., 100., 101., 102., 103., 104., 105.],
          [106., 107., 108., 109., 110., 111., 112.],
          [113., 114., 115., 116., 117., 118., 119.],
          [120., 121., 122., 123., 124., 125., 126.]],
 
         [[127., 12

In [22]:
t = t[3:, :, :]
t.shape

torch.Size([0, 6, 7])

In [31]:
torch.stack([t, t], dim=3).shape

torch.Size([5, 6, 7, 2])

In [17]:
t[1:]

tensor([[[169., 170., 171., 172., 173., 174., 175.],
         [176., 177., 178., 179., 180., 181., 182.],
         [183., 184., 185., 186., 187., 188., 189.],
         [190., 191., 192., 193., 194., 195., 196.],
         [197., 198., 199., 200., 201., 202., 203.],
         [204., 205., 206., 207., 208., 209., 210.]]])

In [18]:
t[1:, :, :]

tensor([[[169., 170., 171., 172., 173., 174., 175.],
         [176., 177., 178., 179., 180., 181., 182.],
         [183., 184., 185., 186., 187., 188., 189.],
         [190., 191., 192., 193., 194., 195., 196.],
         [197., 198., 199., 200., 201., 202., 203.],
         [204., 205., 206., 207., 208., 209., 210.]]])

tensor, scalar, vector, matrix

ndim, shape/size()

rand (int only), zeros, ones, zeros_like, arange

device, dtype, requires_grad

add, mul, sub, div. matmul/mm/@

argmax, argmin

reshape, view (same memory), stack



In [3]:
import torch

tensor = torch.zeros(1, 1, 2, 3)

tensor, tensor.shape

(tensor([[[[0., 0., 0.],
           [0., 0., 0.]]]]),
 torch.Size([1, 1, 2, 3]))

In [12]:
tensor = tensor.squeeze()
tensor, tensor.shape

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.Size([2, 3]))

In [16]:
tensor.unsqueeze(dim=2).shape

torch.Size([2, 3, 1])

In [19]:
torch.permute(tensor, (1, 0)), tensor

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

PyTorch and NumPy

In [20]:
import torch
import numpy as np

In [22]:
array = np.arange(1., 8.)
tensor = torch.arange(1., 8.)
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [25]:
tensor = torch.from_numpy(array).type(torch.float32)
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [28]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

Reproducbility

In [29]:
tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)

print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.7916, 0.0810, 0.9970, 0.9920],
        [0.9509, 0.5894, 0.8619, 0.7179],
        [0.9436, 0.4556, 0.9363, 0.9602]])
tensor([[0.1904, 0.0688, 0.6228, 0.6336],
        [0.4871, 0.5572, 0.0706, 0.9763],
        [0.0435, 0.7664, 0.4120, 0.4531]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [31]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(3, 4)

tensor_C, tensor_D, tensor_C == tensor_D


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [1]:
!nvidia-smi

Fri Aug 16 20:42:48 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch

torch.cuda.is_available()

True

In [3]:
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [4]:
torch.cuda.device_count()

1

In [6]:
tensor = torch.tensor([1, 2, 3], device="cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [8]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [12]:
tensor_cpu = tensor_gpu.cpu()
tensor_cpu.numpy()

array([1, 2, 3])

cuda, cpu <-> gpu